-- Cards: the 52 cards and the Joker, with where each face's art lives.
--
-- GENERATED by scripts/generate-cards-migration.mjs from the engine's own card
-- names. Do not edit by hand; rerun the script, and `--check` catches drift.
-- image_path is relative to the card-art Storage bucket.

create table public.cards (
  code       text primary key,
  name       text not null unique,
  rank       text not null,
  suit       text,
  is_red     boolean not null,
  image_path text not null unique,
  created_at timestamptz not null default now(),
  constraint cards_suit check (suit in ('Hearts', 'Clubs', 'Diamonds', 'Spades')),
  constraint cards_joker_has_no_suit check ((code = 'JOK') = (suit is null)),
  constraint cards_red_matches_suit check (is_red = coalesce(suit in ('Hearts', 'Diamonds'), false))
);

insert into public.cards (code, name, rank, suit, is_red, image_path) values
  ('10C', 'Ten of Clubs', '10', 'Clubs', false, 'v1/10C.svg'),
  ('10D', 'Ten of Diamonds', '10', 'Diamonds', true, 'v1/10D.svg'),
  ('10H', 'Ten of Hearts', '10', 'Hearts', true, 'v1/10H.svg'),
  ('10S', 'Ten of Spades', '10', 'Spades', false, 'v1/10S.svg'),
  ('2C', 'Two of Clubs', '2', 'Clubs', false, 'v1/2C.svg'),
  ('2D', 'Two of Diamonds', '2', 'Diamonds', true, 'v1/2D.svg'),
  ('2H', 'Two of Hearts', '2', 'Hearts', true, 'v1/2H.svg'),
  ('2S', 'Two of Spades', '2', 'Spades', false, 'v1/2S.svg'),
  ('3C', 'Three of Clubs', '3', 'Clubs', false, 'v1/3C.svg'),
  ('3D', 'Three of Diamonds', '3', 'Diamonds', true, 'v1/3D.svg'),
  ('3H', 'Three of Hearts', '3', 'Hearts', true, 'v1/3H.svg'),
  ('3S', 'Three of Spades', '3', 'Spades', false, 'v1/3S.svg'),
  ('4C', 'Four of Clubs', '4', 'Clubs', false, 'v1/4C.svg'),
  ('4D', 'Four of Diamonds', '4', 'Diamonds', true, 'v1/4D.svg'),
  ('4H', 'Four of Hearts', '4', 'Hearts', true, 'v1/4H.svg'),
  ('4S', 'Four of Spades', '4', 'Spades', false, 'v1/4S.svg'),
  ('5C', 'Five of Clubs', '5', 'Clubs', false, 'v1/5C.svg'),
  ('5D', 'Five of Diamonds', '5', 'Diamonds', true, 'v1/5D.svg'),
  ('5H', 'Five of Hearts', '5', 'Hearts', true, 'v1/5H.svg'),
  ('5S', 'Five of Spades', '5', 'Spades', false, 'v1/5S.svg'),
  ('6C', 'Six of Clubs', '6', 'Clubs', false, 'v1/6C.svg'),
  ('6D', 'Six of Diamonds', '6', 'Diamonds', true, 'v1/6D.svg'),
  ('6H', 'Six of Hearts', '6', 'Hearts', true, 'v1/6H.svg'),
  ('6S', 'Six of Spades', '6', 'Spades', false, 'v1/6S.svg'),
  ('7C', 'Seven of Clubs', '7', 'Clubs', false, 'v1/7C.svg'),
  ('7D', 'Seven of Diamonds', '7', 'Diamonds', true, 'v1/7D.svg'),
  ('7H', 'Seven of Hearts', '7', 'Hearts', true, 'v1/7H.svg'),
  ('7S', 'Seven of Spades', '7', 'Spades', false, 'v1/7S.svg'),
  ('8C', 'Eight of Clubs', '8', 'Clubs', false, 'v1/8C.svg'),
  ('8D', 'Eight of Diamonds', '8', 'Diamonds', true, 'v1/8D.svg'),
  ('8H', 'Eight of Hearts', '8', 'Hearts', true, 'v1/8H.svg'),
  ('8S', 'Eight of Spades', '8', 'Spades', false, 'v1/8S.svg'),
  ('9C', 'Nine of Clubs', '9', 'Clubs', false, 'v1/9C.svg'),
  ('9D', 'Nine of Diamonds', '9', 'Diamonds', true, 'v1/9D.svg'),
  ('9H', 'Nine of Hearts', '9', 'Hearts', true, 'v1/9H.svg'),
  ('9S', 'Nine of Spades', '9', 'Spades', false, 'v1/9S.svg'),
  ('AC', 'Ace of Clubs', 'A', 'Clubs', false, 'v1/AC.svg'),
  ('AD', 'Ace of Diamonds', 'A', 'Diamonds', true, 'v1/AD.svg'),
  ('AH', 'Ace of Hearts', 'A', 'Hearts', true, 'v1/AH.svg'),
  ('AS', 'Ace of Spades', 'A', 'Spades', false, 'v1/AS.svg'),
  ('JC', 'Jack of Clubs', 'J', 'Clubs', false, 'v1/JC.svg'),
  ('JD', 'Jack of Diamonds', 'J', 'Diamonds', true, 'v1/JD.svg'),
  ('JH', 'Jack of Hearts', 'J', 'Hearts', true, 'v1/JH.svg'),
  ('JOK', 'Joker', 'JOK', null, false, 'v1/JOK.svg'),
  ('JS', 'Jack of Spades', 'J', 'Spades', false, 'v1/JS.svg'),
  ('KC', 'King of Clubs', 'K', 'Clubs', false, 'v1/KC.svg'),
  ('KD', 'King of Diamonds', 'K', 'Diamonds', true, 'v1/KD.svg'),
  ('KH', 'King of Hearts', 'K', 'Hearts', true, 'v1/KH.svg'),
  ('KS', 'King of Spades', 'K', 'Spades', false, 'v1/KS.svg'),
  ('QC', 'Queen of Clubs', 'Q', 'Clubs', false, 'v1/QC.svg'),
  ('QD', 'Queen of Diamonds', 'Q', 'Diamonds', true, 'v1/QD.svg'),
  ('QH', 'Queen of Hearts', 'Q', 'Hearts', true, 'v1/QH.svg'),
  ('QS', 'Queen of Spades', 'Q', 'Spades', false, 'v1/QS.svg');

-- Reference data. Readable without an account so the demo build can use it.
alter table public.cards enable row level security;

revoke all on public.cards from anon, authenticated;
grant select on public.cards to anon, authenticated;

create policy "cards: anyone may read the deck"
  on public.cards for select to anon, authenticated
  using (true);
